# Site settings
title:       The Hobby Compass
email:       soleblaze@exploits.sexy
author:      Kevin Burns
description: "A place to talk about my various projects"
baseurl:     ""
url:         "http://skyshadows.net"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

gems: [jekyll-paginate]

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: soleblaze
bitbucket_username:
stackoverflow_id:
twitter_username: soleblaze
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
